# Generated by Django 6.0.5 on 2026-05-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_threshold_kwh', models.DecimalField(decimal_places=2, default=3000, max_digits=12)),
                ('spike_threshold_percent', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='energy.building')),
            ],
            options={
                'ordering': ['building__name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('monthly_threshold', 'Monthly Threshold Exceeded'), ('daily_spike', 'Daily Spike Detected')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('alert_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='energy.building')),
                ('energy_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='energy.energyconsumption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
