# Generated by Django 6.0.5 on 2026-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_threshold_kwh', models.DecimalField(decimal_places=2, default=3000, max_digits=12)),
                ('spike_threshold_percent', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threshold Defaults',
                'verbose_name_plural': 'Threshold Defaults',
            },
        ),
    ]
